#  This will be the seed data

//  Top 20 in frequency:
chineseCharsLib1 = [
	{
		"character": "是",
        "deck_id": 1,
		"definition": "to be; indeed, right, yes; okay",
		"pinyin": "shì",
		"decomposition": "⿱日疋",
		"hint": "To speak 日 directly 疋",
	},
	{
		"character": "的",
        "deck_id": 1,
		"definition": "aim, goal; of; possessive particle; -self suffix",
		"pinyin": "de",
		"decomposition": "⿰白勺",
		"hint": "⿰白勺",
	},
	{
		"character": "一",
        "deck_id": 1,
		"definition": "one; a, an; alone",
		"pinyin": "yī",
		"decomposition": "？",
		"hint": "Represents heaven (天), earth (旦), or the number 1",
	},
	{
		"character": "不",
        "deck_id": 1,
		"definition": "no, not, un-; negative prefix",
		"pinyin": "bù",
		"decomposition": "⿱一？",
		"hint": "A bird flying toward the sky 一",
	},
	{
		"character": "了",
        "deck_id": 1,
		"definition": "clear; to finish; particle of completed action",
		"pinyin": "le or liǎo",
		"decomposition": "⿱乛亅",
		"hint": "A child swaddled in blanklets; compare 子",
	},
	{
		"character": "在",
        "deck_id": 1,
		"definition":
			"at, in, on; to exist; used to indicate the present progressive tense",
		"pinyin": "zài",
		"decomposition": "⿸才土",
		"hint": "earth",
	},
	{
		"character": "人",
        "deck_id": 1,
		"definition": "man, person; people",
		"pinyin": "rén",
		"decomposition": "？",
		"hint": "The legs of a human being",
	},
	{
		"character": "有",
        "deck_id": 1,
		"definition": "to have, to own, to possess; to exist",
		"pinyin": "yǒu",
		"decomposition": "⿸？月",
		"hint": "我有钱！ ￥",
	},
	{
		"character": "我",
        "deck_id": 1,
		"definition": "I, me, my; our, us",
		"pinyin": "wǒ",
		"decomposition": "⿰扌戈",
		"hint": "A hand 扌 holding a weapon 戈",
	},
	{
		"character": "他",
        "deck_id": 1,
		"definition": "other, another; he, she, it",
		"pinyin": "tā",
		"decomposition": "⿰亻也",
		"hint": 'An additional, "also" 也  person 亻',
	},
	{
		"character": "这",
        "deck_id": 1,
		"definition": "this, these; such; here",
		"pinyin": "zhè",
		"decomposition": "⿺辶文",
		"hint": "⿺辶文",
	},
	{
		"character": "个",
        "deck_id": 1,
		"definition": "this, that; single; measure word for individuals",
		"pinyin": ["gè"],
		"decomposition": "⿱人丨",
		"hint": "A tally 丨 of people 人",
	},
	{
		"character": "们",
        "deck_id": 1,
		"definition": "plural marker for pronouns and some nouns",
		"pinyin": "men",
		"decomposition": "⿰亻门",
		"hint": "people",
	},
	{
		"character": "中",
        "deck_id": 1,
		"definition":
			"central; center, middle; amidst; to hit (target), to attain; China; Chinese",
		"pinyin": "zhōng",
		"decomposition": "⿻口丨",
		"hint": "A line 丨 through the center of a box 口",
	},
	{
		"character": "来",
        "deck_id": 1,
		"definition": "to arrive, to come, to return; in the future, later on",
		"pinyin": "lái",
		"decomposition": "⿻未丷",
		"hint": "A wheat plant that has not yet borne fruit; compare 來",
	},
	{
		"character": "上",
        "deck_id": 1,
		"definition": "above, on top, superior; to go up; to attend; previous",
		"pinyin": "shàng",
		"decomposition": "⿱⺊一",
		"hint": "One stroke on top of another; compare 下 (below)",
	},
	{
		"character": "大",
        "deck_id": 1,
		"definition": "big, great, vast, high, deep",
		"pinyin": "dà",
		"decomposition": "⿻一人",
		"hint": "A man 人 with outstretched arms",
	},
	{
		"character": "为",
        "deck_id": 1,
		"definition": "to do, to act; to handle, to govern; to be",
		"pinyin": "wèi",
		"decomposition": "⿻丶⿴力丶",
        "hint": "⿻丶⿴力丶"
	},
	{
		"character": "和",
        "deck_id": 1,
		"definition": "harmony, peace; calm, peaceful",
		"pinyin": "hé",
		"decomposition": "⿰禾口",
		"hint": "mouth",
	},
	{
		"character": "国",
        "deck_id": 1,
		"definition": "country, nation, state; national",
		"pinyin": "guó",
		"decomposition": "⿴囗玉",
		"hint": "Treasure 玉 within a country's borders 囗",
	},
]
  op.bulk_insert(characters_table, [
	{
		"character": "地",
        "deck_id": 2,
		"definition": "earth, ground, soil; land, region; structural particle used before a verb",
		"pinyin": "de",
		"decomposition": "⿰土也",
		"hint": "earth; 一, 丨, 一, 乚, ㇆, 丨",
	},
	{
		"character": "到",
        "deck_id": 2,
		"definition": "to go to, to arrive",
		"pinyin": "dào",
		"decomposition": "⿰至刂",
		"hint": "arrive; radical:刂",
	},
	{
		"character": "以",
        "deck_id": 2,
		"definition": "according to; so as to; because of; then",
		"pinyin": "yǐ",
		"decomposition": "⿰？人",
		"hint": "⿰？人",
	},
	{
		"character": "说",
        "deck_id": 2,
		"definition": "to speak, to say; to scold, to upbraid",
		"pinyin": "shuō",
		"decomposition": "⿰讠兑",
		"hint": "speech; radical: 讠",
	},
	{
		"character": "时",
        "deck_id": 2,
		"definition": "time, season; period, era, age",
		"pinyin": "shí",
		"decomposition": "⿰日寸",
		"hint": "day; radical: 日",
	},
	{
		"character": "要",
        "deck_id": 2,
		"definition":
			"yao1 - to demand/to request/to coerce; yao4 - important/vital/to want/will/going to (as future auxiliary)/may/must/(used in a comparison) must be/probably",
		"pinyin": "yào",
		"decomposition": "⿱覀女",
		"hint": "A woman 女 with hands on her waist 覀",
	},
	{
		"character": "就",
        "deck_id": 2,
		"definition": " at once/right away/only/just (emphasis)/as early as/already/as soon as/then/in that case/as many as/even if/to approach/to move towards/to undertake",
		"pinyin": "jiù",
		"decomposition": "京, 尤",
		"hint": "specialty;  亠 (lid), 口 (mouth), 小 (small), 尢 (lame), 丶 (dot)",
	},
	{
		"character": "出",
        "deck_id": 2,
		"definition": "to go out, to send out; stand; produce",
		"pinyin": "chū",
		"decomposition": "⿱屮凵",
		"hint": "A sprout 屮 growing out of a container 凵",
	},
	{
		"character": "会",
        "deck_id": 2,
		"definition": "can/be possible/be able to/will/be likely to/be sure to/to assemble/to meet/to gather/to see/union/group",
		"pinyin": "huì",
		"decomposition": "⿱人云",
		"hint": "People 人 speaking 云",
	},
	{
		"character": "可",
        "deck_id": 2,
		"definition": "may, can, -able; possibly",
		"pinyin": "kě",
		"decomposition": "⿻丁口",
		"hint": '"hint":"vigorous"; "semantic":"丁",,"phonetic":"口"',
	},
	{
		"character": "也",
        "deck_id": 2,
		"definition": "also, too",
		"pinyin": "yě",
		"decomposition": "⿻？乚",
		"hint": "乚, ㇆, 丨",
	},
	{
		"character": "你",
        "deck_id": 2,
		"definition": "you (informal, as opposed to courteous 您)",
		"pinyin": "nǐ",
		"decomposition": "⿰亻尔",
		"hint": "Pronoun 尔 for a person "
	},
	{
		"character": "对",
        "deck_id": 2,
		"definition": "correct, right; facing, opposed",
		"pinyin": "duì",
		"decomposition": "⿰又寸",
		"hint": "A pair 又 of hands 寸",
	},
	{
		"character": "生",
        "deck_id": 2,
		"definition":"life, to be born/to give birth/life/to grow/raw, uncooked",
		"pinyin": "shēng",
		"decomposition": "⿻一土",
		"hint": "A shoot 屮 growing in the soil 土",
	},
	{
		"character": "能",
        "deck_id": 2,
		"definition": "to be able to/to be capable of/ability/capability/able/capable/can possibly/(usually used in the negative) to have the possibility of",
		"pinyin": "néng",
		"decomposition": "⿰⿱厶⺼⿱匕匕",
		"hint": "A bear's head 厶, body ⺼, and claws 匕",
	},
	{
		"character": "而",
        "deck_id": 2,
		"definition": "and, and then, and yet; but",
		"pinyin": "ér",
		"decomposition": "丆, 𦉫",
		"hint": "一, 丿, 冂, 丨",
	},
	{
		"character": "子",
        "deck_id": 2,
		"definition": "son, child; seed, egg; fruit; small thing",
		"pinyin": "zi",
		"decomposition": "⿻了一",
		"hint": "A child in a wrap, with outstretched arms but bundled legs",
	},
	{
		"character": "那",
        "deck_id": 2,
		"definition": "that, that one, those",
		"pinyin": "nà",
		"decomposition": "㇆, 二, 丨, 阝",
        "hint": "㇆, 二, 丨, 丨, ㇌"
	},
	{
		"character": "得",
        "deck_id": 2,
		"definition": " structural particle: used after a verb (or adjective as main verb), linking it to following phrase indicating effect, degree, possibility etc; to obtain, to get, to acquire; suitable, proper; ready",
		"pinyin": "dé",
		"decomposition": "⿰彳⿱旦",
		"hint": "A hand 寸 grabbing a shell 旦",
	},
	{
		"character": "于",
        "deck_id": 2,
		"definition": "at, in, on; to, from; alas!",
		"pinyin": "yú",
		"decomposition": "⿻二亅",
		"hint": " 一, 一, 丨, 亅",
	},
]
) 
# Level 3
  op.bulk_insert(characters_table, [
	{
		"character": "着",
        "deck_id": 3,
		"definition": "to make a move, to take action; aspect particle indicating action in progress",
		"pinyin": "zhe",
		"decomposition": "⿸羊目",
		"hint": "radical: 目",
	},
	{
		"character": "下",
        "deck_id": 3,
		"definition": "below, underneath; inferior; to bring down; next",
		"pinyin": "xià",
		"decomposition": ""⿱一卜",
		"hint": "One stroke under another",
	},
	{
		"character": "自",
        "deck_id": 3,
		"definition": "self; private, personal; from",
		"pinyin": "zì",
		"decomposition": "⿻目",
		"hint": "A nose; in China, people refer to themselves by pointing to their noses",
	},
	{
		"character": "之",
        "deck_id": 3,
		"definition": "marks preceding phrase as modifier of following phrase; it, him her, them; to go to",
		"pinyin": "zhī",
		"decomposition": "⿱丶？",
		"hint": "A foot meaning \"to follow\"; cursive version of 止",
	},
	{
		"character": "年",
        "deck_id": 3,
		"definition": "year; anniversary; a person's age",
		"pinyin": "nián",
		"decomposition": "⿻干？",
		"hint": "A man 干 carrying grain, representing the annual harvest",
	},
	{
		"character": "过",
        "deck_id": 3,
		"definition": "pass; to go across, to pass through",
		"pinyin": "guò",
		"decomposition": "⿺辶寸",
		"hint": "walk",
	},
	{
		"character": "发",
        "deck_id": 3,
		"definition": "to issue, to dispatch, to send out; hair",
		"pinyin": "fā",
		"decomposition": "⿸？又",
		"hint": "radical:又",
	},
	{
		"character": "后",
        "deck_id": 3,
		"definition": "after; behind, rear; descendants",
		"pinyin": "hòu",
		"decomposition": "⿸？口",
		"hint": "口",
	},
	{
		"character": "作",
        "deck_id": 3,
		"definition": "to make; to write, to compose; to act, to perform",
		"pinyin": "zuò",
		"decomposition": "⿰亻乍",
		"hint": "A person 亻 making something for the first time",
	},
	{
		"character": "里",
        "deck_id": 3,
		"definition": "unit of distance equal to 0.5km; village; lane",
		"pinyin": "lǐ",
		"decomposition": "⿱田土",
		"hint": "Unit of measure for farm 田 land 土",
	},
	{
		"character": "用",
        "deck_id": 3,
		"definition": "to use, to employ, to apply; use",
		"pinyin": "yòng",
		"decomposition": "⿵冂",
		"hint": "用",
	},
	{
		"character": "道",
        "deck_id": 3,
		"definition": "method, way; path, road",
		"pinyin": "dào",
		"decomposition": "⿺辶首",
		"hint": "walk"
	},
	{
		"character": "行",
        "deck_id": 3,
		"definition": "to go, to walk, to move; professional",
		"pinyin": "xíng",
		"decomposition": "⿰彳亍",
		"hint": "To take small steps 亍 with one's feet 彳",
	},
	{
		"character": "所",
        "deck_id": 3,
		"definition":"place, location; \'that which\', a particle introducing a passive clause",
		"pinyin": "suǒ",
		"decomposition": "⿰户斤",
		"hint": "An axe 斤 swung at a door 户",
	},
	{
		"character": "然",
        "deck_id": 3,
		"definition": "certainly; naturally; suddenly",
		"pinyin": "rán",
		"decomposition": "⿱肰灬",
		"hint": "fire",
	},
	{
		"character": "家",
        "deck_id": 3,
		"definition": "house, home, residence; family",
		"pinyin": "jiā",
		"decomposition": "⿱宀豕",
		"hint": "roof",
	},
	{
		"character": "种",
        "deck_id": 3,
		"definition": "race, kind, breed; seed; to plant",
		"pinyin": "zhǒng",
		"decomposition": "⿰禾中",
		"hint": "grain",
	},
	{
		"character": "事",
        "deck_id": 3,
		"definition": "affair, matter, business; to serve; accident, incident",
		"pinyin": "shì",
		"decomposition": "⿻⿳一口彐亅",
        "hint": "亅"
	},
	{
		"character": "成",
        "deck_id": 3,
		"definition": "to accomplish; to become; to complete, to finish; to succeed",
		"pinyin": "chéng",
		"decomposition": "⿰丁戈",
		"hint": "戈",
	},
	{
		"character": "方",
        "deck_id": 3,
		"definition": "surname Fang; square, rectangle; side; region; flag",
		"pinyin": "fāng",
		"decomposition": "⿱亠?",
		"hint": "skipping",
	},
]
) 