"""empty message

Revision ID: 5bf2d9da8485
Revises: 8041fa5f96a3
Create Date: 2021-01-08 13:57:33.465100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf2d9da8485'
down_revision = '8041fa5f96a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'deck_id')
    )
    # op.drop_column('decks', 'times_completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('times_completed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('completions')
    # ### end Alembic commands ###
