"""empty message

Revision ID: 8041fa5f96a3
Revises: c5500972f0d6
Create Date: 2021-01-07 18:29:42.024504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8041fa5f96a3'
down_revision = 'c5500972f0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'decks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decks', type_='foreignkey')
    op.drop_column('decks', 'user_id')
    # ### end Alembic commands ###
