"""decks and their characters

Revision ID: c5500972f0d6
Revises: 5137f7b65bc6
Create Date: 2021-01-07 12:47:44.286357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5500972f0d6'
down_revision = '5137f7b65bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    decks_table = op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(decks_table, [{"name":"Level 1 - Top 20"}]) 
    op.bulk_insert(decks_table, [{"name":"Level 2"}]) 

    characters_table = op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(), nullable=True),
    sa.Column('pinyin', sa.String(), nullable=True),
    sa.Column('definition', sa.String(), nullable=True),
    sa.Column('hint', sa.String(), nullable=True),
    sa.Column('decomposition', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint('id')
    )

	## Deck seeding: 
	#Level 1 - Top 20
    op.bulk_insert(characters_table, [
	{
		"character": "是",
        "deck_id": 1,
		"definition": "to be; indeed, right, yes; okay",
		"pinyin": "shì",
		"decomposition": "⿱日疋",
		"hint": "To speak 日 directly 疋",
	},
	{
		"character": "的",
        "deck_id": 1,
		"definition": "aim, goal; of; possessive particle; -self suffix",
		"pinyin": "de",
		"decomposition": "⿰白勺",
		"hint": "⿰白勺",
	},
	{
		"character": "一",
        "deck_id": 1,
		"definition": "one; a, an; alone",
		"pinyin": "yī",
		"decomposition": "？",
		"hint": "Represents heaven (天), earth (旦), or the number 1",
	},
	{
		"character": "不",
        "deck_id": 1,
		"definition": "no, not, un-; negative prefix",
		"pinyin": "bù",
		"decomposition": "⿱一？",
		"hint": "A bird flying toward the sky 一",
	},
	{
		"character": "了",
        "deck_id": 1,
		"definition": "clear; to finish; particle of completed action",
		"pinyin": "le or liǎo",
		"decomposition": "⿱乛亅",
		"hint": "A child swaddled in blanklets; compare 子",
	},
	{
		"character": "在",
        "deck_id": 1,
		"definition":
			"at, in, on; to exist; used to indicate the present progressive tense",
		"pinyin": "zài",
		"decomposition": "⿸才土",
		"hint": "earth",
	},
	{
		"character": "人",
        "deck_id": 1,
		"definition": "man, person; people",
		"pinyin": "rén",
		"decomposition": "？",
		"hint": "The legs of a human being",
	},
	{
		"character": "有",
        "deck_id": 1,
		"definition": "to have, to own, to possess; to exist",
		"pinyin": "yǒu",
		"decomposition": "⿸？月",
		"hint": "我有钱！ ￥",
	},
	{
		"character": "我",
        "deck_id": 1,
		"definition": "I, me, my; our, us",
		"pinyin": "wǒ",
		"decomposition": "⿰扌戈",
		"hint": "A hand 扌 holding a weapon 戈",
	},
	{
		"character": "他",
        "deck_id": 1,
		"definition": "other, another; he, she, it",
		"pinyin": "tā",
		"decomposition": "⿰亻也",
		"hint": 'An additional, "also" 也  person 亻',
	},
	{
		"character": "这",
        "deck_id": 1,
		"definition": "this, these; such; here",
		"pinyin": "zhè",
		"decomposition": "⿺辶文",
		"hint": "⿺辶文",
	},
	{
		"character": "个",
        "deck_id": 1,
		"definition": "this, that; single; measure word for individuals",
		"pinyin": "gè",
		"decomposition": "⿱人丨",
		"hint": "A tally 丨 of people 人",
	},
	{
		"character": "们",
        "deck_id": 1,
		"definition": "plural marker for pronouns and some nouns",
		"pinyin": "men",
		"decomposition": "⿰亻门",
		"hint": "people",
	},
	{
		"character": "中",
        "deck_id": 1,
		"definition":
			"central; center, middle; amidst; to hit (target), to attain; China; Chinese",
		"pinyin": "zhōng",
		"decomposition": "⿻口丨",
		"hint": "A line 丨 through the center of a box 口",
	},
	{
		"character": "来",
        "deck_id": 1,
		"definition": "to arrive, to come, to return; in the future, later on",
		"pinyin": "lái",
		"decomposition": "⿻未丷",
		"hint": "A wheat plant that has not yet borne fruit; compare 來",
	},
	{
		"character": "上",
        "deck_id": 1,
		"definition": "above, on top, superior; to go up; to attend; previous",
		"pinyin": "shàng",
		"decomposition": "⿱⺊一",
		"hint": "One stroke on top of another; compare 下 (below)",
	},
	{
		"character": "大",
        "deck_id": 1,
		"definition": "big, great, vast, high, deep",
		"pinyin": "dà",
		"decomposition": "⿻一人",
		"hint": "A man 人 with outstretched arms",
	},
	{
		"character": "为",
        "deck_id": 1,
		"definition": "to do, to act; to handle, to govern; to be",
		"pinyin": "wèi",
		"decomposition": "⿻丶⿴力丶",
        "hint": "⿻丶⿴力丶"
	},
	{
		"character": "和",
        "deck_id": 1,
		"definition": "and, with; calm, peaceful",
		"pinyin": "hé",
		"decomposition": "⿰禾口",
		"hint": "mouth",
	},
	{
		"character": "国",
        "deck_id": 1,
		"definition": "country, nation, state; national",
		"pinyin": "guó",
		"decomposition": "⿴囗玉",
		"hint": "Treasure 玉 within a country's borders 囗",
	},
]
) 
## second deck
    op.bulk_insert(characters_table, [
	{
		"character": "地",
        "deck_id": 2,
		"definition": "earth, ground, soil; land, region; structural particle used before a verb",
		"pinyin": "de",
		"decomposition": "⿰土也",
		"hint": "earth; 一, 丨, 一, 乚, ㇆, 丨",
	},
	{
		"character": "到",
        "deck_id": 2,
		"definition": "to go to, to arrive",
		"pinyin": "dào",
		"decomposition": "⿰至刂",
		"hint": "arrive; radical:刂",
	},
	{
		"character": "以",
        "deck_id": 2,
		"definition": "according to; so as to; because of; then",
		"pinyin": "yǐ",
		"decomposition": "⿰？人",
		"hint": "⿰？人",
	},
	{
		"character": "说",
        "deck_id": 2,
		"definition": "to speak, to say; to scold, to upbraid",
		"pinyin": "shuō",
		"decomposition": "⿰讠兑",
		"hint": "speech; radical: 讠",
	},
	{
		"character": "时",
        "deck_id": 2,
		"definition": "time, season; period, era, age",
		"pinyin": "shí",
		"decomposition": "⿰日寸",
		"hint": "day; radical: 日",
	},
	{
		"character": "要",
        "deck_id": 2,
		"definition":
			"yao1 - to demand/to request/to coerce; yao4 - important/vital/to want/will/going to (as future auxiliary)/may/must/(used in a comparison) must be/probably",
		"pinyin": "yào",
		"decomposition": "⿱覀女",
		"hint": "A woman 女 with hands on her waist 覀",
	},
	{
		"character": "就",
        "deck_id": 2,
		"definition": " at once/right away/only/just (emphasis)/as early as/already/as soon as/then/in that case/as many as/even if/to approach/to move towards/to undertake",
		"pinyin": "jiù",
		"decomposition": "京, 尤",
		"hint": "specialty;  亠 (lid), 口 (mouth), 小 (small), 尢 (lame), 丶 (dot)",
	},
	{
		"character": "出",
        "deck_id": 2,
		"definition": "to go out, to send out; stand; produce",
		"pinyin": "chū",
		"decomposition": "⿱屮凵",
		"hint": "A sprout 屮 growing out of a container 凵",
	},
	{
		"character": "会",
        "deck_id": 2,
		"definition": "can/be possible/be able to/will/be likely to/be sure to/to assemble/to meet/to gather/to see/union/group",
		"pinyin": "huì",
		"decomposition": "⿱人云",
		"hint": "People 人 speaking 云",
	},
	{
		"character": "可",
        "deck_id": 2,
		"definition": "may, can, -able; possibly",
		"pinyin": "kě",
		"decomposition": "⿻丁口",
		"hint": '"hint":"vigorous"; "semantic":"丁",,"phonetic":"口"',
	},
	{
		"character": "也",
        "deck_id": 2,
		"definition": "also, too",
		"pinyin": "yě",
		"decomposition": "⿻？乚",
		"hint": "乚, ㇆, 丨",
	},
	{
		"character": "你",
        "deck_id": 2,
		"definition": "you (informal, as opposed to courteous 您)",
		"pinyin": "nǐ",
		"decomposition": "⿰亻尔",
		"hint": "Pronoun 尔 for a person "
	},
	{
		"character": "对",
        "deck_id": 2,
		"definition": "correct, right; facing, opposed",
		"pinyin": "duì",
		"decomposition": "⿰又寸",
		"hint": "A pair 又 of hands 寸",
	},
	{
		"character": "生",
        "deck_id": 2,
		"definition":"life, to be born/to give birth/life/to grow/raw, uncooked",
		"pinyin": "shēng",
		"decomposition": "⿻一土",
		"hint": "A shoot 屮 growing in the soil 土",
	},
	{
		"character": "能",
        "deck_id": 2,
		"definition": "to be able to/to be capable of/ability/capability/able/capable/can possibly/(usually used in the negative) to have the possibility of",
		"pinyin": "néng",
		"decomposition": "⿰⿱厶⺼⿱匕匕",
		"hint": "A bear's head 厶, body ⺼, and claws 匕",
	},
	{
		"character": "而",
        "deck_id": 2,
		"definition": "and, and then, and yet; but",
		"pinyin": "ér",
		"decomposition": "丆, 𦉫",
		"hint": "一, 丿, 冂, 丨",
	},
	{
		"character": "子",
        "deck_id": 2,
		"definition": "son, child; seed, egg; fruit; small thing",
		"pinyin": "zi",
		"decomposition": "⿻了一",
		"hint": "A child in a wrap, with outstretched arms but bundled legs",
	},
	{
		"character": "那",
        "deck_id": 2,
		"definition": "that, that one, those",
		"pinyin": "nà",
		"decomposition": "㇆, 二, 丨, 阝",
        "hint": "㇆, 二, 丨, 丨, ㇌"
	},
	{
		"character": "得",
        "deck_id": 2,
		"definition": " structural particle: used after a verb (or adjective as main verb), linking it to following phrase indicating effect, degree, possibility etc; to obtain, to get, to acquire; suitable, proper; ready",
		"pinyin": "dé",
		"decomposition": "⿰彳⿱旦",
		"hint": "A hand 寸 grabbing a shell 旦",
	},
	{
		"character": "于",
        "deck_id": 2,
		"definition": "at, in, on; to, from; alas!",
		"pinyin": "yú",
		"decomposition": "⿻二亅",
		"hint": " 一, 一, 丨, 亅",
	},
]
) 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    op.drop_table('decks')
	# pass
    # ### end Alembic commands ###
