"""decks and their characters

Revision ID: c5500972f0d6
Revises: 5137f7b65bc6
Create Date: 2021-01-07 12:47:44.286357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5500972f0d6'
down_revision = '5137f7b65bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    decks_table = op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('times_completed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(decks_table, [{"name":"Top 20", "times_completed":0 }]) 

    characters_table = op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(), nullable=True),
    sa.Column('pinyin', sa.String(), nullable=True),
    sa.Column('definition', sa.String(), nullable=True),
    sa.Column('hint', sa.String(), nullable=True),
    sa.Column('decomposition', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(characters_table, [
	{
		"character": "是",
        "deck_id": 1,
		"definition": "to be; indeed, right, yes; okay",
		"pinyin": "shì",
		"decomposition": "⿱日疋",
		"hint": "To speak 日 directly 疋",
	},
	{
		"character": "的",
        "deck_id": 1,
		"definition": "aim, goal; of; possessive particle; -self suffix",
		"pinyin": "de",
		"decomposition": "⿰白勺",
		"hint": "⿰白勺",
	},
	{
		"character": "一",
        "deck_id": 1,
		"definition": "one; a, an; alone",
		"pinyin": "yī",
		"decomposition": "？",
		"hint": "Represents heaven (天), earth (旦), or the number 1",
	},
	{
		"character": "不",
        "deck_id": 1,
		"definition": "no, not, un-; negative prefix",
		"pinyin": "bù",
		"decomposition": "⿱一？",
		"hint": "A bird flying toward the sky 一",
	},
	{
		"character": "了",
        "deck_id": 1,
		"definition": "clear; to finish; particle of completed action",
		"pinyin": "le or liǎo",
		"decomposition": "⿱乛亅",
		"hint": "A child swaddled in blanklets; compare 子",
	},
	{
		"character": "在",
        "deck_id": 1,
		"definition":
			"at, in, on; to exist; used to indicate the present progressive tense",
		"pinyin": "zài",
		"decomposition": "⿸才土",
		"hint": "earth",
	},
	{
		"character": "人",
        "deck_id": 1,
		"definition": "man, person; people",
		"pinyin": "rén",
		"decomposition": "？",
		"hint": "The legs of a human being",
	},
	{
		"character": "有",
        "deck_id": 1,
		"definition": "to have, to own, to possess; to exist",
		"pinyin": "yǒu",
		"decomposition": "⿸？月",
		"hint": "我有钱！ ￥",
	},
	{
		"character": "我",
        "deck_id": 1,
		"definition": "I, me, my; our, us",
		"pinyin": "wǒ",
		"decomposition": "⿰扌戈",
		"hint": "A hand 扌 holding a weapon 戈",
	},
	{
		"character": "他",
        "deck_id": 1,
		"definition": "other, another; he, she, it",
		"pinyin": "tā",
		"decomposition": "⿰亻也",
		"hint": 'An additional, "also" 也  person 亻',
	},
	{
		"character": "这",
        "deck_id": 1,
		"definition": "this, these; such; here",
		"pinyin": "zhè",
		"decomposition": "⿺辶文",
		"hint": "⿺辶文",
	},
	{
		"character": "个",
        "deck_id": 1,
		"definition": "this, that; single; measure word for individuals",
		"pinyin": "gè",
		"decomposition": "⿱人丨",
		"hint": "A tally 丨 of people 人",
	},
	{
		"character": "们",
        "deck_id": 1,
		"definition": "plural marker for pronouns and some nouns",
		"pinyin": "men",
		"decomposition": "⿰亻门",
		"hint": "people",
	},
	{
		"character": "中",
        "deck_id": 1,
		"definition":
			"central; center, middle; amidst; to hit (target), to attain; China; Chinese",
		"pinyin": "zhōng",
		"decomposition": "⿻口丨",
		"hint": "A line 丨 through the center of a box 口",
	},
	{
		"character": "来",
        "deck_id": 1,
		"definition": "to arrive, to come, to return; in the future, later on",
		"pinyin": "lái",
		"decomposition": "⿻未丷",
		"hint": "A wheat plant that has not yet borne fruit; compare 來",
	},
	{
		"character": "上",
        "deck_id": 1,
		"definition": "above, on top, superior; to go up; to attend; previous",
		"pinyin": "shàng",
		"decomposition": "⿱⺊一",
		"hint": "One stroke on top of another; compare 下 (below)",
	},
	{
		"character": "大",
        "deck_id": 1,
		"definition": "big, great, vast, high, deep",
		"pinyin": "dà",
		"decomposition": "⿻一人",
		"hint": "A man 人 with outstretched arms",
	},
	{
		"character": "为",
        "deck_id": 1,
		"definition": "to do, to act; to handle, to govern; to be",
		"pinyin": "wèi",
		"decomposition": "⿻丶⿴力丶",
        "hint": "⿻丶⿴力丶"
	},
	{
		"character": "和",
        "deck_id": 1,
		"definition": "and, with; calm, peaceful",
		"pinyin": "hé",
		"decomposition": "⿰禾口",
		"hint": "mouth",
	},
	{
		"character": "国",
        "deck_id": 1,
		"definition": "country, nation, state; national",
		"pinyin": "guó",
		"decomposition": "⿴囗玉",
		"hint": "Treasure 玉 within a country's borders 囗",
	},
]
) 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    op.drop_table('decks')
    # ### end Alembic commands ###
